### ISSUE TITLE
Startup Fails: JsonLdError Unexpected response code [404]

### ISSUE THREAD

**Issue by ipa-big** [eclipse-tractusx/managed-identity-wallet#341]
### Current Behavior
When starting wallet (version 0.4.0) with helm chart from umbrella it fails with the following error message:

```
2024-07-31T18:22:43.721Z ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'walletController' defined in URL [jar:file:/app/miw-latest.jar!/BOOT-INF/classes!/org/eclipse/tractusx/managedidentitywallets/controller/WalletController.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'walletService': Invocation of init method failed
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:801) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:240) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:950) ~[spring-context-6.0.14.jar!/:6.0.14]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:616) ~[spring-context-6.0.14.jar!/:6.0.14]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.1.6.jar!/:3.1.6]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738) ~[spring-boot-3.1.6.jar!/:3.1.6]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440) ~[spring-boot-3.1.6.jar!/:3.1.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-3.1.6.jar!/:3.1.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.6.jar!/:3.1.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-3.1.6.jar!/:3.1.6]
	at org.eclipse.tractusx.managedidentitywallets.ManagedIdentityWalletsApplication.main(ManagedIdentityWalletsApplication.java:43) ~[classes!/:latest]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[miw-latest.jar:latest]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[miw-latest.jar:latest]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[miw-latest.jar:latest]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[miw-latest.jar:latest]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'walletService': Invocation of init method failed
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:222) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1762) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:910) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788) ~[spring-beans-6.0.14.jar!/:6.0.14]
	... 27 common frames omitted
Caused by: java.lang.RuntimeException: JsonLdError[code=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED]., message=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].]
	at org.eclipse.tractusx.ssi.lib.proof.transform.LinkedDataTransformer.toDataset(LinkedDataTransformer.java:94) ~[cx-ssi-lib-0.0.18.jar!/:na]
	at org.eclipse.tractusx.ssi.lib.proof.transform.LinkedDataTransformer.canocliztion(LinkedDataTransformer.java:62) ~[cx-ssi-lib-0.0.18.jar!/:na]
	at org.eclipse.tractusx.ssi.lib.proof.transform.LinkedDataTransformer.transform(LinkedDataTransformer.java:56) ~[cx-ssi-lib-0.0.18.jar!/:na]
	at org.eclipse.tractusx.ssi.lib.proof.LinkedDataProofGenerator.createProof(LinkedDataProofGenerator.java:89) ~[cx-ssi-lib-0.0.18.jar!/:na]
	at org.eclipse.tractusx.managedidentitywallets.utils.CommonUtils.createVerifiableCredential(CommonUtils.java:139) ~[classes!/:latest]
	at org.eclipse.tractusx.managedidentitywallets.utils.CommonUtils.getHoldersCredential(CommonUtils.java:89) ~[classes!/:latest]
	at org.eclipse.tractusx.managedidentitywallets.service.IssuersCredentialService.issueBpnCredential(IssuersCredentialService.java:198) ~[classes!/:latest]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-6.0.14.jar!/:6.0.14]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.0.14.jar!/:6.0.14]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.0.14.jar!/:6.0.14]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751) ~[spring-aop-6.0.14.jar!/:6.0.14]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-6.0.14.jar!/:6.0.14]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391) ~[spring-tx-6.0.14.jar!/:6.0.14]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-6.0.14.jar!/:6.0.14]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.14.jar!/:6.0.14]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751) ~[spring-aop-6.0.14.jar!/:6.0.14]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703) ~[spring-aop-6.0.14.jar!/:6.0.14]
	at org.eclipse.tractusx.managedidentitywallets.service.IssuersCredentialService$$SpringCGLIB$$0.issueBpnCredential(<generated>) ~[classes!/:latest]
	at org.eclipse.tractusx.managedidentitywallets.service.WalletService.createWallet(WalletService.java:278) ~[classes!/:latest]
	at org.eclipse.tractusx.managedidentitywallets.service.WalletService$1.doInTransactionWithoutResult(WalletService.java:297) ~[classes!/:latest]
	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:36) ~[spring-tx-6.0.14.jar!/:6.0.14]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-6.0.14.jar!/:6.0.14]
	at org.eclipse.tractusx.managedidentitywallets.service.WalletService.createAuthorityWallet(WalletService.java:289) ~[classes!/:latest]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMethod.invoke(InitDestroyAnnotationBeanPostProcessor.java:457) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:401) ~[spring-beans-6.0.14.jar!/:6.0.14]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:219) ~[spring-beans-6.0.14.jar!/:6.0.14]
	... 40 common frames omitted
Caused by: com.apicatalog.jsonld.JsonLdError: There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].
	at com.apicatalog.jsonld.context.ActiveContextBuilder.fetch(ActiveContextBuilder.java:539) ~[titanium-json-ld-1.3.3.jar!/:na]
	at com.apicatalog.jsonld.context.ActiveContextBuilder.create(ActiveContextBuilder.java:174) ~[titanium-json-ld-1.3.3.jar!/:na]
	at com.apicatalog.jsonld.expansion.ObjectExpansion.initLocalContext(ObjectExpansion.java:200) ~[titanium-json-ld-1.3.3.jar!/:na]
	at com.apicatalog.jsonld.expansion.ObjectExpansion.expand(ObjectExpansion.java:102) ~[titanium-json-ld-1.3.3.jar!/:na]
	at com.apicatalog.jsonld.expansion.Expansion.compute(Expansion.java:119) ~[titanium-json-ld-1.3.3.jar!/:na]
	at com.apicatalog.jsonld.processor.ExpansionProcessor.expand(ExpansionProcessor.java:124) ~[titanium-json-ld-1.3.3.jar!/:na]
	at com.apicatalog.jsonld.processor.ToRdfProcessor.toRdf(ToRdfProcessor.java:69) ~[titanium-json-ld-1.3.3.jar!/:na]
	at com.apicatalog.jsonld.api.ToRdfApi.get(ToRdfApi.java:166) ~[titanium-json-ld-1.3.3.jar!/:na]
	at org.eclipse.tractusx.ssi.lib.proof.transform.LinkedDataTransformer.toDataset(LinkedDataTransformer.java:92) ~[cx-ssi-lib-0.0.18.jar!/:na]
	... 73 common frames omitted
Caused by: com.apicatalog.jsonld.JsonLdError: Unexpected response code [404]
	at com.apicatalog.jsonld.loader.DefaultHttpLoader.loadDocument(DefaultHttpLoader.java:95) ~[titanium-json-ld-1.3.3.jar!/:na]
	at com.apicatalog.jsonld.loader.HttpLoader.loadDocument(HttpLoader.java:6) ~[titanium-json-ld-1.3.3.jar!/:na]
	at org.eclipse.tractusx.ssi.lib.model.RemoteDocumentLoader.loadDocument(RemoteDocumentLoader.java:157) ~[cx-ssi-lib-0.0.18.jar!/:na]
	at com.apicatalog.jsonld.context.ActiveContextBuilder.fetch(ActiveContextBuilder.java:535) ~[titanium-json-ld-1.3.3.jar!/:na]
	... 81 common frames omitted
```

### Expected Behavior
Wallet does not fail at startup.

### Steps To Reproduce
Umbrella helm Chart (excerpt):

```
---
apiVersion: v2
name: umbrella
sources:
  - https://github.com/eclipse-tractusx/tractus-x-umbrella
type: application
version: 1.0.0

dependencies:
...
  - name: managed-identity-wallet
    repository: https://eclipse-tractusx.github.io/charts/dev
    version: 0.4.0
    condition: managed-identity-wallet.enabled
...
```
values file

```
managed-identity-wallet:
  enabled: true
  seeding:
    enabled: false
    clientId: sa-cl5-custodian-2
    clientSecret: UIqawwoohsvZ6AZOd1llLhnsUTKMWe4D
  miw:
    host: "managed-identity-wallets.tx.test"
    authorityWallet:
      bpn: "BPNL00000003CRHK"
      name: "Catena-X"
    database:
      host: "{{ .Release.Name }}-miw-postgres"
      secret: "{{ .Release.Name }}-miw-postgres"
    keycloak:
      url: "http://centralidp.tx.test/auth"
      realm: "CX-Central"
      clientId: "Cl5-CX-Custodian"
    ssi:
      enforceHttpsInDidWebResolution: "false"
  postgresql:
    nameOverride: miw-postgres
    primary:
      persistence:
        enabled: false
        size: 1Gi
    auth:
      password: "dbpasswordmiw"
      enablePostgresUser: true
      postgresPassword: "dbpasswordmiw"
  keycloak:
    enabled: false
  livenessProbe:
    initialDelaySeconds: 90
  readinessProbe:
    initialDelaySeconds: 90
  ingress:
    enabled: true
    hosts:
      - host: "managed-identity-wallets.tx.test"
        paths:
          - path: "/"
            pathType: "ImplementationSpecific"
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/cors-allow-origin: http://portal.tx.test
      nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
      nginx.ingress.kubernetes.io/cors-allow-methods: GET
      nginx.ingress.kubernetes.io/enable-cors: "true"
```

**Comment by JohnnyH666** [comment]
Hi, mate. I’m experiencing the same issue. Have you found a solution? The MIW worked for me with the Helm chart from the umbrella before, but it seems it has not been able to deploy since yesterday. The pod log indicates that it cannot load the JSON content from the URL mentioned in the README file: https://catenax-ng.github.io/product-core-schemas/businessPartnerData.json, I can't open this in my browser neither.

**Comment by matbmoser** [comment]
Hi @ipa-big, we are working on it!

Here there is the official bug ticket: https://github.com/eclipse-tractusx/managed-identity-wallet/issues/342

**Comment by matbmoser** [comment]
Hi @ipa-big can you please try again? In teory the issue shall be solved.

**Comment by ipa-big** [comment]
@matbmoser Sorry it took me a while to reevaluate. Yes, right now it is working as expected.

@JohnnyH666 Regarding your question "Have you found a solution?" : before the catena x orga was still unavailable (https://github.com/orgs/catenax-ng) I tried to remove the references to the external catena-x-ng schemas like this:

```
# values.yaml
...
managed-identity-wallet:
  enabled: true
  envs:
    VC_SCHEMA_LINK: "https://www.w3.org/2018/credentials/v1"
    SUMMARY_VC_SCHEMA_LINK: "https://www.w3.org/2018/credentials/v1"
...
```
With this values file the wallet starts without any issues but of course fails during runtime when interacting with the wallet because the schemas are required for processing incoming requests.

What I'm also trying right now is to setup a nginx webserver which hosts the schema files. Then i rewrite the urls so they point to my own webserver. This makes a setup independent from external sources (like the catena-x-ng repo). But I still have some issues with wrong content-type and json-ld context being null.

There are also alternative repos which host similar/the same schema files here (in case catena-x-ng disappears again):
- https://github.com/koptan/product-core-schemas (fork of catena-x-ng)
- https://github.com/big-data-spaces/product-core-schemas (fork of koptan)

**Comment by matbmoser** [comment]
@ipa-big good to know that it worked for you!

The new MIW v0.5.0 does not contain this problem because the Summary Credentials are discontinued there.
Good to know there are forks from this credential, however I would still continue to use this schema https://catenax-ng.github.io/product-core-schemas/SummaryVC.json

Until a better solution is provided from Tractus-X side.

Keep up with the updates in this ticket #342 !

Please confirm if we can close this ticket already :)

**Comment by ipa-big** [comment]
you can close this ticket. 

I will try version 0.5.0 and continue with trying to host the schema files locally but still no luck with this approach

**Comment by matbmoser** [comment]
Please note that the 0.5.0 is compatible with just the EDC 0.8.0

**Comment by ipa-big** [comment]
> Please note that the 0.5.0 is compatible with just the EDC 0.8.0

Oh ok. Good to know. In this case this is not an option for me

**Comment by matbmoser** [comment]
After the 0.6.0 MIW support is broken until the 0.8.0 that is now in testing phase for the R24.12!

Good luck with the problem solving! In theory should work the same as before, we have tested and it is working, if you find another problem then just reported and let's see what it is!
