### ISSUE TITLE
Add Wallet results in LOADING_REMOTE_CONTEXT_FAILED if egress is blocked

### ISSUE THREAD

**Issue by arunsworld** [eclipse-tractusx/managed-identity-wallet#89]
When running managed identity wallet in an environment without internet access, calls to creating a new wallet by doing a POST to /api/wallets results in JsonLdError[code=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED]., message=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].]

java.lang.RuntimeException: JsonLdError[code=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED]., message=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].]
	at org.eclipse.tractusx.ssi.lib.proof.transform.LinkedDataTransformer.toDataset(LinkedDataTransformer.java:82) ~[cx-ssi-lib-0.0.16.jar!/:na]
	at org.eclipse.tractusx.ssi.lib.proof.transform.LinkedDataTransformer.transform(LinkedDataTransformer.java:50) ~[cx-ssi-lib-0.0.16.jar!/:na]
	at org.eclipse.tractusx.ssi.lib.proof.LinkedDataProofGenerator.createProof(LinkedDataProofGenerator.java:70) ~[cx-ssi-lib-0.0.16.jar!/:na]
	at org.eclipse.tractusx.managedidentitywallets.utils.CommonUtils.createVerifiableCredential(CommonUtils.java:128) ~[classes!/:latest]
	at org.eclipse.tractusx.managedidentitywallets.utils.CommonUtils.getHoldersCredential(CommonUtils.java:85) ~[classes!/:latest]
	at org.eclipse.tractusx.managedidentitywallets.service.IssuersCredentialService.issueBpnCredential(IssuersCredentialService.java:198) ~[classes!/:latest]

Is it possible to pre-load the JSON LD schemas or even list out the destinations to which egress needs to be allowed?

**Comment by pmoscode** [comment]
In this PR, the most important context are preloaded:
https://github.com/eclipse-tractusx/managed-identity-wallet/pull/100

Perhaps this is what you are looking for?

**Comment by arunsworld** [comment]
We pulled the code and compiled it locally to test. It does not appear to have helped. MIW still attempts to reach out to all the following domains: www.w3.org, catenax-ng.github.io, w3id.org, w3c.github.io.

In fact, things appear to have gotten distinctly worse. On a fresh install MIW refuses to start even when egress is enabled.

```
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-10-12T03:13:42.483Z ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'walletController' defined in URL [jar:file:/app/miw-latest.jar!/BOOT-INF/classes!/org/eclipse/tractusx/managedidentitywallets/controller/WalletController.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'walletService': Invocation of init method failed
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-6.0.11.jar!/:6.0.11]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245) ~[spring-beans-6.0.11.jar!/:6.0.11]
....
Caused by: java.lang.RuntimeException: JsonLdError[code=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED]., message=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].]
	at org.eclipse.tractusx.ssi.lib.proof.transform.LinkedDataTransformer.toDataset(LinkedDataTransformer.java:82) ~[cx-ssi-lib-0.0.16.jar!/:na]
	at org.eclipse.tractusx.ssi.lib.proof.transform.LinkedDataTransformer.transform(LinkedDataTransformer.java:50) ~[cx-ssi-lib-0.0.16.jar!/:na]
	at org.eclipse.tractusx.ssi.lib.proof.LinkedDataProofGenerator.createProof(LinkedDataProofGenerator.java:70) ~[cx-ssi-lib-0.0.16.jar!/:na]
	at org.eclipse.tractusx.managedidentitywallets.utils.CommonUtils.createVerifiableCredential(CommonUtils.java:128) ~[classes!/:latest]
	at org.eclipse.tractusx.managedidentitywallets.utils.CommonUtils.getHoldersCredential(CommonUtils.java:85) ~[classes!/:latest]
	at org.eclipse.tractusx.managedidentitywallets.service.IssuersCredentialService.updateSummeryCredentials(IssuersCredentialService.java:533) ~[classes!/:latest]
	at org.eclipse.tractusx.managedidentitywallets.service.IssuersCredentialService.issueBpnCredential(IssuersCredentialService.java:209) ~[classes!/:latest]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
```

**Comment by florianrusch-zf** [comment]
I run into the same issue with the 0.1.0 images.

**Comment by arunsworld** [comment]
I believe that image is a month old. Our miw component was working fine even a week or so ago and now it's completely broken which means the EDCs are useless as well. I suspect something changed outside of the code. We need to instrument the ssi-agent-lib to get to the bottom of it, but it appears to us that miw fundamentally depends on RemoteDocumentLoader during JWT token validations and if the context is an http URL and not in it's cache, it goes out to the internet, at which point we're totally at the mercy of how APIs outside the code are behaving. Should such a critical component not rely entirely on locally stored file contexts instead?

**Comment by Julian-Marco** [comment]
Same issue here even when I run it on main. Also tried it with 0.1.1 and 0.1.0, but it doesn*t help. I used the docker setup.

**Comment by arunsworld** [comment]
Looks like same issue as reported in #103.

The URLs that are reached:

* https://www.w3.org/2018/credentials/v1
* https://catenax-ng.github.io/product-core-schemas/businessPartnerData.json
* https://w3id.org/security/suites/jws-2020/v1
* https://w3c.github.io/vc-jws-2020/contexts/v1/
* https://catenax-ng.github.io/product-core-schemas/SummaryVC.json

**Comment by borisrizov-zf** [comment]
The 0.2.0-develop.1 release should have fixed the issues, BUT still uses egress.

**Comment by Julian-Marco** [comment]
I receive a similar error message when using this version: https://github.com/eclipse-tractusx/managed-identity-wallet/releases/tag/v0.2.0

WARNING 2023-11-01T08:49:30.7532659 Error expanding JSON-LD structure
JsonLdError[code=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED]., message=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].]
	at com.apicatalog.jsonld.context.ActiveContextBuilder.fetch(ActiveContextBuilder.java:539)
	at com.apicatalog.jsonld.context.ActiveContextBuilder.create(ActiveContextBuilder.java:174)
	at com.apicatalog.jsonld.expansion.ObjectExpansion.initLocalContext(ObjectExpansion.java:200)
	at com.apicatalog.jsonld.expansion.ObjectExpansion.expand(ObjectExpansion.java:102)
	at com.apicatalog.jsonld.expansion.Expansion.compute(Expansion.java:119)
	at com.apicatalog.jsonld.processor.ExpansionProcessor.expand(ExpansionProcessor.java:124)
	at com.apicatalog.jsonld.api.ExpansionApi.get(ExpansionApi.java:131)
	at org.eclipse.edc.jsonld.TitaniumJsonLd.expand(TitaniumJsonLd.java:67)
	at org.eclipse.tractusx.edc.iam.ssi.miw.credentials.SsiMiwCredentialClient.mapClaim(SsiMiwCredentialClient.java:107)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1625)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Collections.java:1650)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.eclipse.tractusx.edc.iam.ssi.miw.credentials.SsiMiwCredentialClient.extractClaims(SsiMiwCredentialClient.java:96)
	at org.eclipse.tractusx.edc.iam.ssi.miw.credentials.SsiMiwCredentialClient.validate(SsiMiwCredentialClient.java:57)
	at org.eclipse.tractusx.edc.iam.ssi.identity.SsiTokenValidationService.validate(SsiTokenValidationService.java:41)
	at org.eclipse.tractusx.edc.iam.ssi.identity.SsiIdentityService.verifyJwtToken(SsiIdentityService.java:43)
	at org.eclipse.edc.protocol.dsp.api.configuration.message.DspRequestHandlerImpl.updateResource(DspRequestHandlerImpl.java:145)
	at org.eclipse.edc.protocol.dsp.negotiation.api.controller.DspNegotiationApiController.createAgreement(DspNegotiationApiController.java:278)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:357)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:193)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: JsonLdError[code=The document could not be loaded or parsed [code=LOADING_DOCUMENT_FAILED]., message=URL scheme [https] is not supported.]
	at com.apicatalog.jsonld.loader.SchemeRouter.loadDocument(SchemeRouter.java:59)
	at org.eclipse.edc.jsonld.TitaniumJsonLd$CachedDocumentLoader.loadDocument(TitaniumJsonLd.java:146)
	at com.apicatalog.jsonld.context.ActiveContextBuilder.fetch(ActiveContextBuilder.java:535)
	... 79 more
WARNING 2023-11-01T08:49:30.7543899 There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].
SEVERE 2023-11-01T08:49:30.8116186 Failed to extract credential subject from the membership credential
SEVERE 2023-11-01T08:49:30.8116186 Failed to extract credential subject from the membership credential
DEBUG 2023-11-01T08:49:30.8116186 DSP: Unauthorized: Failed to extract credential subject from the membership credential, Failed to extract credential subject from the membership credential

**Comment by borisrizov-zf** [comment]
Just to clarify: The MIW is not supposed to be used as a local/personal wallet; it still needs internet access to load the JSON-LD schemas for validation, the reason being that there are still changes happening to some of the schema files and it's unstable at the moment.
Please ensure you allow egress to all context files used in your credential.

**Comment by borisrizov-zf** [comment]
I'm closing this due to inactivity.
